function measurement_corrected = correct_slope(measurement, time, start_lat_idx, end_lat_idx)
    measurement_fitted = fit(time(start_lat_idx:end_lat_idx),...
        measurement(start_lat_idx:end_lat_idx), 'poly1');
    measurement_corrected = measurement(start_lat_idx:end_lat_idx) - ...
        measurement_fitted.p1*time(start_lat_idx:end_lat_idx) + ...
        measurement_fitted.p1*time(start_lat_idx);
end