function [requirements_values, requirements_met]= requirements_validation_TSI3(L1B_HR, L1B_ML,chd)
%% SIRS-275 10 meter width lead elevation
% falta

%% SIRS-305: Range random error < 0.08 m (HR)
[requirements_values.range_rand_err_HR_ku, requirements_met.range_rand_err_HR_ku] = ...
    random_range_error(L1B_HR.range_ku, L1B_HR.altitude_ku, chd.height_ssh_ku, ...
    chd.random_range_error, [chd.ku_start_lat_idx_HR(1) chd.ku_start_lat_idx_HR(3)], ...
    [chd.ku_end_lat_HR(1) chd.ku_end_lat_HR(3)]);

% Ka band 
[requirements_values.range_rand_err_HR_ka, requirements_met.range_rand_err_HR_ka] = ...
    random_range_error(L1B_HR.range_ka, L1B_HR.altitude_ka, chd.height_ssh_ka, ...
    chd.random_range_error, [chd.ka_start_lat_idx_HR(1) chd.ka_start_lat_idx_HR(3)], ...
    [chd.ka_end_lat_HR(1) chd.ka_end_lat_HR(3)]);

%% SIRS-305: Range random error < 0.08 m (ML)
[requirements_values.range_rand_err_ML_ku, requirements_met.range_rand_err_ML_ku] = ...
    random_range_error(L1B_ML.range_ku, L1B_ML.altitude_ku, chd.height_ssh_ku, ...
    chd.random_range_error, [chd.ku_start_lat_idx_ML_FF(1) chd.ku_start_lat_idx_ML_FF(3)], ...
    [chd.ku_end_lat_ML_FF(1) chd.ku_end_lat_ML_FF(3)]);

% Ka band 
[requirements_values.range_rand_err_ML_ka, requirements_met.range_rand_err_ML_ka] = ...
    random_range_error(L1B_ML.range_ka, L1B_ML.altitude_ka, chd.height_ssh_ka, ...
    chd.random_range_error, [chd.ka_start_lat_idx_ML_FF(1) chd.ka_start_lat_idx_ML_FF(3)], ...
    [chd.ka_end_lat_ML_FF(1) chd.ka_end_lat_ML_FF(3)]);

end