function [requirements_values, requirements_met]= requirements_validation_TLI3(GR,chd)
%% SIRS-286 The accuracy of elevations retrieved from ice sheets, glaciers and ice caps shall be better than 2 metres.
% Ku band
[requirements_values.land_ice_elevation_accuracy_ku, requirements_met.land_ice_elevation_accuracy_ku] = ...
    land_ice_elevation_accuracy(chd.ku_start_lat_idx(2), chd.ku_end_lat_idx(2), chd.land_ice_elevation, ...
    chd.elevation_accuracy, GR.land_ice_elevation_ku);
% Ka band
% [requirements_values.land_ice_elevation_accuracy_ka, requirements_met.land_ice_elevation_accuracy_ka] = ...
%     land_ice_elevation_accuracy(chd.ka_start_lat_idx(2), chd.ka_end_lat_idx(2), chd.land_ice_elevation, ...
%     chd.elevation_accuracy, GR.land_ice_elevation_ka);
end